Fix: Ansible sanity check return-syntax-error for os_conversion_host_info module
Documented return type in os_conversion_host_info module was not complete.

Updating the return types of 'str' for the 'address','id', 'name' and 'status' keys
resolves this failure.

Exact error message being fixed:

```
ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.address.type: required key not provided
@ data['openstack_conversion_host']['contains']['address']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.id.type: required key not provided
@ data['openstack_conversion_host']['contains']['id']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.name.type: required key not provided
@ data['openstack_conversion_host']['contains']['name']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.status.type: required key not provided
@ data['openstack_conversion_host']['contains']['status']['type'].
Got None
```