Fix: Ansible sanity check no-log-needed for argument 'ssh_key_path'
Argument 'ssh_key_path' in argument_spec was by default configured to
log but as recommended by the no-log-needed sanity check this path
could indeed be secret.
As such we can mark this argument as no_log=True to remove this
argument's value from any logs.

Example of exact error message being fixed:

```
ERROR: plugins/modules/import_workload_dst_failure_cleanup.py:0:0: no-log-needed:
Argument 'ssh_key_path' in argument_spec could be a secret, though doesn't have `no_log` set
```